In [2]:
import numpy as np

### Creación de arrays

1.  Genera un *array* bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array. 


In [6]:
#Creo el array
array_random_bi=np.random.randint(34,99, (4,3))
print(f'El array es:\n{array_random_bi}\n')

#Compruebo dimensiones
print(f'Las dimensiones de este array son: {array_random_bi.ndim}')

#Compruebo tipos de datos
print(f'El tipo de datos de este array es: {array_random_bi.dtype}')

El array es:
[[79 82 55]
 [49 87 76]
 [53 93 73]
 [66 72 66]]

Las dimensiones de este array son: 2
El tipo de datos de este array es: int64


2. Crea dos *arrays* (unidimensional, bidimensional) usando el método `np.array()`. 

    Las listas para crear los *arrays* son las siguientes

    ```python
    lista1 = [34,56,71,98, 10]
    lista2 = [[23,45,89, 56], [12,43,82,44]]
    ```

    **Bonus** Haz una pequeña descripción de cada *array* usando los métodos de exploración de *arrays* que hemos aprendido.



In [ ]:
lista1 = [34,56,71,98, 10]
array_uni=np.array(lista1)
print(f'Este es el array uni: {array_uni}')

lista2 = [[23,45,89, 56], [12,43,82,44]]
array_bi=np.array(lista2)
print(f'Este es el array bi:\n {array_bi}')

Este es el array uni: [34 56 71 98 10]
Este es el array bi:
 [[23 45 89 56]
 [12 43 82 44]]


In [ ]:
#Descripción del array unidimensional
print(f'El array uni es: {array_uni}')
print(f'El array uni tiene la forma: {array_uni.shape}')
print(f'El array uni tiene {array_uni.ndim} dimensiones')
print(f'El array uni tiene {array_uni.size} elementos')
print(f'El array uni tiene el tipo de datos: {array_uni.dtype}')

El array uni es: [34 56 71 98 10]
El array uni tiene la forma: (5,)
El array uni tiene 1 dimensiones
El array uni tiene 5 elementos
El array uni tipo el tipo de datos: int64


In [ ]:
#Descripción del array bidimensional
print(f'El array bi es:\n{array_bi}')
print(f'El array bi tiene la forma: {array_bi.shape}')
print(f'El array bi tiene {array_bi.ndim} dimensiones')
print(f'El array bi tiene {array_bi.size} elementos')
print(f'El array bi tiene el tipo de datos: {array_bi.dtype}')

El array bi es:
[[23 45 89 56]
 [12 43 82 44]]
El array bi tiene la forma: (2, 4)
El array bi tiene 2 dimensiones
El array bi tiene 8 elementos
El array bi tiene el tipo de datos: int64


### Indexación

1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Los elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

In [3]:
#Creo array uni random
array_uni=np.arange(1,51)
print(f'El array uni es:\n{array_uni}\n')

#Selecciono el primer elemento
print(f'El primer elemento es: {array_uni[0]}\n')

#Selecciono los elementos en posición impar
print(f'Los elementos en posición impar son:\n{array_uni[1::2]}\n')

#Selecciono los cuatro primeros elementos
print(f'Los cuatro primeros elementos son:\n{array_uni[:4]}\n')

#Selecciono los tres últimos elementos
print(f'Los tres últimos elementos son:\n{array_uni[-3:]}\n')

#Selecciono los elementos entre el 4 y el 8 incluido
print(f'Los elementos del 4 al 8 incluido son:\n{array_uni[4:9]}')

El array uni es:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

El primer elemento es: 1

Los elementos en posición impar son:
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]

Los cuatro primeros elementos son:
[1 2 3 4]

Los tres últimos elementos son:
[48 49 50]

Los elementos del 4 al 8 incluido son:
[5 6 7 8 9]


2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [4]:
#Creo array bi random, de 4x5, con números enteros de 0 a 99
array_bi=np.random.randint(0,100, (4,5))
print(f'El array bi es:\n{array_bi}\n')

#Selecciono la fila 1
print(f'La fila 1, con todas las columnas es:\n{array_bi[0]}\n')

#Selecciono todas las filas pares
print(f'Las filas pares son:\n{array_bi[::2]}\n')

#Selecciono la primera columna de todas las filas
print(f'La primera columna de todas las filas es:\n{array_bi[:,0]}')

El array bi es:
[[41 49 64 35 58]
 [28  3 66 75 66]
 [11 16 20 13 31]
 [21 25 28 51 49]]

La fila 1, con todas las columnas es:
[41 49 64 35 58]

Las filas pares son:
[[41 49 64 35 58]
 [11 16 20 13 31]]

La primera columna de todas las filas es:
[41 28 11 21]


### Filtros y operaciones

1. Crea un *array* bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y: 

    - Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".


    - Los valores de mi array bidimensional multiplicalos por el escalar 10.


In [ ]:
#Creo array bi random, 5x4 (20 elementos),  entre 0 y 50
bidi=np.random.randint(0,51, (5,4))
print(f'El array es:\n{bidi}\n')

#Creo filtro para valores mayores de 30 o menores de 10
result=np.where((bidi >30) | (bidi <10), 'objetivo', 'no es mi objetivo')
print(f'Cumple condición:\n{result}\n')

#Multiplico por el escalar 10
escalar=10
result_escalar=np.multiply(bidi, escalar)
print(f'El Resultado de multiplicar por el escalar es:\n{result_escalar}')

El array es:
[[35 42 18 34]
 [ 0 31  0 42]
 [ 0 48 41 49]
 [40  1  7 29]
 [26 41 18 41]]

Cumple condición:
[['objetivo' 'objetivo' 'no es mi objetivo' 'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'objetivo']
 ['objetivo' 'objetivo' 'objetivo' 'no es mi objetivo']
 ['no es mi objetivo' 'objetivo' 'no es mi objetivo' 'objetivo']]

El Resultado de multiplicar por el escalar es:
[[350 420 180 340]
 [  0 310   0 420]
 [  0 480 410 490]
 [400  10  70 290]
 [260 410 180 410]]


2. Crea un nuevo *array* de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

    - Suma el primer array con el segundo.


    - Aplicar la potencia para el primer array elevado al segundo.

In [ ]:
print(f'El primer array es:\n{bidi}')
#Creo array bi random, 5x4 (20 elementos),  entre 0 y 5
bidimi=np.random.randint(0,5, (5,4))
print(f'El nuevo array es:\n{bidimi}\n')

#Suma
sum=np.add(bidi, bidimi)
print(f'El resultado de la suma de ambos arrays es:\n{sum}\n')

#Potencia
power=np.power(bidi, bidimi)
print(f'El resultado del primer array elevado al segundo array es:\n{power}')

El primer array es:
[[35 42 18 34]
 [ 0 31  0 42]
 [ 0 48 41 49]
 [40  1  7 29]
 [26 41 18 41]]
El nuevo array es:
[[3 0 0 4]
 [3 4 1 3]
 [1 4 2 0]
 [1 4 4 1]
 [2 3 4 4]]

El resultado de la suma de ambos arrays es:
[[38 42 18 38]
 [ 3 35  1 45]
 [ 1 52 43 49]
 [41  5 11 30]
 [28 44 22 45]]

El resultado del primer array elevado al segundo array es:
[[  42875       1       1 1336336]
 [      0  923521       0   74088]
 [      0 5308416    1681       1]
 [     40       1    2401      29]
 [    676   68921  104976 2825761]]


### Funciones

1. En este ejercicio vamos a tratar de usar algunos de los métodos aprendidos. 

    - Crea un *array*, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

    - Calcula: 

        - La media de los elementos
        - La media de las columnas y redondéalo a dos decimales
        - El valor máximo de cada fila
        - El valor mínimo de cada fila
        - Hay algun valor que sea mayor que 90 en tu *array* 
        - Donde los podemos encontrar, cuáles son sus índices
        - Ordena el *array* de mayor a menor

In [10]:
#Creo array bidi, 3x4, entre 0-100
array_funciones=np.random.randint(0,101, (3,4))
print(f'El array es:\n{array_funciones}')

El array es:
[[20 80 50 92]
 [86 93 98 37]
 [68 80 64 18]]


In [11]:
#Calculo la media de todo el array
mean=np.mean(array_funciones)
mean_round=np.round(mean, 2)
print(f'La media del array es: {mean_round}')

La media del array es: 65.5


In [12]:
#Calculo la media de cada columna
mean_col=np.mean(array_funciones, axis=0)
mean_col_round=np.round(mean_col, 2)
print(f'La media de cada columna es:\n{mean_col_round}')

La media de cada columna es:
[58.   84.33 70.67 49.  ]


In [13]:
#Otra forma de calcular la media redondeada, en un sólo paso
mean_fil_round=np.round(np.mean(array_funciones, axis=1), 2)
print(f'La media de cada fila es:\n{mean_fil_round}')

La media de cada fila es:
[60.5 78.5 57.5]


In [ ]:
#Calculo el máximo de cada fila
max=np.max(array_funciones, axis=1)
print(f'El valor máximo de cada fila es:\n{max}')

El valor máximo de cada fila es:
[47 29 92]


In [ ]:
#Calculo el mínimo de cada fila
print(f'El valor mínimo de cada fila es:\n{np.min(array_funciones, axis=1)}')

El valor mínimo de cada fila es:
[ 3  2 64]


In [14]:
#¿Hay algún valor mayor que 90 en el array?
mayor_90=np.any(array_funciones >90)
print(f'¿Hay algún valor mayor que 90?: {mayor_90}')

¿Hay algún valor mayor que 90?: True


In [15]:
#También puedo averiguarlo con un for
for fila in array_funciones:
    for valor in fila:
        if valor >90:
            hay_mayor_90=True
            break
    if hay_mayor_90:
        break
print(f'¿Hay algún valor mayor que 90?: {hay_mayor_90}')

¿Hay algún valor mayor que 90?: True


In [16]:
#También lo puedo hacer directamente con un if, sin pasar por un for
if mayor_90:
    indices_mayor_90=np.where(array_funciones >90)
    print(f'Los índices en los que hay valores mayores a 90 son:{indices_mayor_90}')

Los índices en los que hay valores mayores a 90 son:(array([0, 1, 1]), array([3, 1, 2]))


In [17]:
#¿Dónde puedo encontrar los valores mayores que 90, cuáles son sus índices?

#Creo una lista vacía para guardar los índices que tienen un valor mayor a 90
indices_mayores_90=[]
#Recorro las filas y, dentro, las columnas
for i in range(array_funciones.shape[0]): #range genera una secuencia de números que representan los índices de las filas
    for j in range(array_funciones.shape[1]):
        if array_funciones[i][j] >90:
            indices_mayores_90.append((i,j))

print(f'Los índices en los que hay valores mayores a 90 son:\n{indices_mayores_90}')

Los índices en los que hay valores mayores a 90 son:
[(0, 3), (1, 1), (1, 2)]


In [ ]:
#Ordeno el array de mayor a menor
print(f'El array original es:\n{array_funciones}\n')
print(f'El array ordenado de mayor a menor es:\n{-np.sort(-array_funciones)}')

El array original es:
[[ 3 33 47 13]
 [19  2  6 29]
 [64 87 92 83]]

El array ordenado de mayor a menor es:
[[47 33 13  3]
 [29 19  6  2]
 [92 87 83 64]]


In [18]:
#También lo puedo ordenar con un flatten, pero entonces lo paso a 1D
print(f'El array origina es:\n{array_funciones}')

array_aplanado=np.sort(array_funciones.flatten())[::-1] #[::-1] invierte el array para obtener el orden de mayor a menor
print(f'el array rodenado de mayor a menor, con un flatten es:\n{array_aplanado}')

El array origina es:
[[20 80 50 92]
 [86 93 98 37]
 [68 80 64 18]]
el array rodenado de mayor a menor, con un flatten es:
[98 93 92 86 80 80 68 64 50 37 20 18]
